version: '3.8'

services:
  api:
    restart: always
    build:
      context: .
      target: development
    container_name: api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    depends_on:
      - database
    networks:
      - backend
    env_file:
      - .env

  database:
    container_name: database
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
volumes:
  api_db_data:
    driver: local